### ISSUE TITLE
Creates confluence1

### ISSUE THREAD

**Issue by joshskains** [sous-chefs/confluence#15]
Is there a reason I can not pre-create confluence with a standardized UID? We have the user created before confluence role is run, and the end result is we get a confluence1 created as well. Is there some settings to the user we can do to avoid that?

**Comment by legal90** [comment]
@joshskains It is still actual for you?
If so, then please tell what cookbook version and recipe do you use?

I suggest that `linux_standalone` should not cause that issue.

**Comment by legal90** [comment]
Closed as inactive.

Please, let us know if this issue will be reproduced again on the latest cookbook version.

**Comment by jtusz** [comment]
In the cookbook version 2.0.0 the problem is still active in case of "installer" install type.

Config: Ubuntu 14.04LTS on AWS OpsWorks
Issue recreation:
1. Initial Confluence deployment with install_type = "installer"
2. Redeployment with same settings

[Redeployment fails with this error (textfile)](https://github.com/parallels-cookbooks/confluence/files/334957/confluence_error_aws_opsworks.txt)

**Comment by legal90** [comment]
Seems like Confluence installer creates a new user (`confluence1`, `confluence2`, ...) in case when the installation dir was changed, but `confluence` account already exists.

I think it may happen if the value of `['confluence']['install_path']` attribute has been changed between redeployments. In this case, the installer tries to install Confluence once again and creates a new user account to avoid the collision with an existing one. But the init script still contains the original user name, "confluence", so the service fails to restart.

@jtusz Could you please double check - was the installation dir changed between redeployments?
