### ISSUE TITLE
Add test-kitchen integration tests to travis

### ISSUE THREAD

**Issue by esciara** [sous-chefs/confluence#5]
Hi there,

Newbie question: I saw that Travis is used, but looking at the [current .travis.yml](https://github.com/bflad/chef-confluence/blob/6a45ec8aecb6c4d43aa5e966f6d4f303f6786a10/.travis.yml) it looks like only foodcritic and rubo tests are run. 

Being a newbie I have no idea what the limits to Travis are... And a wild CI dream would be that the cookbook could be tested running a test-kitchen instance, at least to see whether it installs correctly on at least on flavor of linux, even runs Integration tests with serverspec and/or ATDD tests with Cucumber. Even wilder (unreasonable?) dream would be that it does this on all supported flavors of linux when pushed to master.

Possible?

**Comment by bflad** [comment]
Definitely possible and doable from what I've seen with other cookbooks. I just haven't had time to play. Only possible limitation for test kitchen might be that I'd have to pay for test instances to spin up.

**Comment by esciara** [comment]
Do you have some links so I can have a look? On travis fair use policy too if you have (could not find much info on the subject).

**Comment by esciara** [comment]
Ok, I looked into it... I don't think it can work as installation of vagrant + VM images would pass the [build timeout of 50 minutes](http://docs.travis-ci.com/user/build-configuration/#Build-Timeouts).

So I had a look around and saw what is done on https://github.com/opscode-cookbooks/tomcat for instance. They are using test-kitchen drivers to start servers on the cloud. More details in https://github.com/opscode-cookbooks/tomcat/blob/master/TESTING.md .

Had a try on Digital Ocean with a cookbook of mine. Turns out each test on each machine costs $0.01 .

**Comment by patcon** [comment]
I can work on this. I've got a good template for running test-kitchen tests via travis, using a quarantined digital ocean account specifically for testing

**Comment by legal90** [comment]
@patcon Currently I'm experimenting with Travis+Docker. I think, it will be more convenient. And it's free :)
https://github.com/legal90/confluence/tree/travis-docker
https://travis-ci.org/legal90/confluence/builds/91621505

P.s. I was inspired by Chef's "database" cookbook:
https://github.com/chef-cookbooks/database/blob/master/.travis.yml

**Comment by patcon** [comment]
Nice! fwiw I had some issues that I had to work around when I was trying to test with docker before. Seems like the others have been addressed, but I think the [`init_package`](https://github.com/parallels-cookbooks/confluence/blob/06f80c146473d9d7f2c4a8e229b87c93dd32de1d/recipes/configuration.rb#L33) still acts in a misleading way when you run in docker, as it will show `bash` or something like that instead of a init system. So might be to figure out another way to determine systemd usage

Anyhow, just a heads up. and testing costs on IaaS are essentially negligible, so no need to count that  as a strike against aws or DO if we think they might be more robust :)

EDIT: possibly helpful link about init_package: https://github.com/hw-cookbooks/postgresql/pull/247#issuecomment-115749540

**Comment by patcon** [comment]
If we really want, could even create a library cookbook codifying the detection from pleaserun, or this cookbook:
https://github.com/lusis/chef-logstash/pull/354

**Comment by patcon** [comment]
@legal90 mind converting that branch into a PR so we could talk about what's working and what's not so far? Wondering whether I'm hitting the same issues as you on that branch :)

**Comment by legal90** [comment]
@patcon OK. I'll do it tomorrow

**Comment by gsreynolds** [comment]
@patcon also worth considering [poise-service](https://github.com/poise/poise-service) as an alternative to chef-pleaserun. I've not personally used either but heard good things about poise-service.
